const accounts = [
  { id: 1, clientId: 1, type: "მიმდინარე", currency: "GEL", status: "აქტიური" },
  {
    id: 2,
    clientId: 1,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  { id: 3, clientId: 2, type: "მიმდინარე", currency: "GEL", status: "აქტიური" },
  {
    id: 4,
    clientId: 2,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  { id: 5, clientId: 3, type: "მიმდინარე", currency: "GEL", status: "აქტიური" },
  {
    id: 6,
    clientId: 3,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  { id: 7, clientId: 4, type: "მიმდინარე", currency: "GEL", status: "აქტიური" },
  {
    id: 8,
    clientId: 4,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  { id: 9, clientId: 5, type: "მიმდინარე", currency: "GEL", status: "აქტიური" },
  {
    id: 10,
    clientId: 5,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 11,
    clientId: 6,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 12,
    clientId: 6,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 13,
    clientId: 7,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 14,
    clientId: 7,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 15,
    clientId: 8,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 16,
    clientId: 8,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 17,
    clientId: 9,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 18,
    clientId: 9,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 19,
    clientId: 10,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 20,
    clientId: 10,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 21,
    clientId: 11,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 22,
    clientId: 11,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
  {
    id: 23,
    clientId: 12,
    type: "მიმდინარე",
    currency: "GEL",
    status: "აქტიური",
  },
  {
    id: 24,
    clientId: 12,
    type: "მიმდინარე",
    currency: "USD",
    status: "დახურული",
  },
];

export default accounts;
